### ISSUE TITLE
About the dataset thanks

### ISSUE THREAD

**Issue by lrrll** [Fieldhunter/2020-ZhanJiang-Underwater-Object-Detection-Algorithm-Contest#2]
Hello, I am a student of Ocean University of China. After registering the contest at that time, personal reasons were put on hold, and the data set was not downloaded in time. Because my current research direction is also on sonar, can I share the data set privately? Thanks!

**Comment by Fieldhunter** [comment]
@lrrll Hi lrrll, thanks for your issue. I am very pleasure to share the dataset of the competition. But the competition has two channels: Optical and Sonar. I participated in the optical. So I don't have the sonar dataset, only the optical dataset. I don't know whether the dataset in this part is helpful to you. If you want the optical dataset, please reply to me in this issue next.

**Comment by c464851257** [comment]
您好 可以给我一份光学的数据吗？万分感谢

**Comment by Fieldhunter** [comment]
@c464851257 您好，关于光学的数据集我已上传到Google Drive，您可通过以下地址自行下载：https://drive.google.com/drive/folders/1MHzdxShXW6QdkD_9QmNT9oPUNerMYxDq?usp=sharing

**Comment by c464851257** [comment]
> @c464851257 您好，关于光学的数据集我已上传到Google Drive，您可通过以下地址自行下载：https://drive.google.com/drive/folders/1MHzdxShXW6QdkD_9QmNT9oPUNerMYxDq?usp=sharing

谢谢您，还有一个问题，您对数据进行保证图片比例的resize以后边框用灰条填充，label的处理部分在代码里面没有看见呢

**Comment by Fieldhunter** [comment]
> > @c464851257 您好，关于光学的数据集我已上传到Google Drive，您可通过以下地址自行下载：https://drive.google.com/drive/folders/1MHzdxShXW6QdkD_9QmNT9oPUNerMYxDq?usp=sharing
> 
> 谢谢您，还有一个问题，您对数据进行保证图片比例的resize以后边框用灰条填充，label的处理部分在代码里面没有看见呢

针对灰条填充后的的label处理是有的，在yolo3/utils.py中：
```
# https://github.com/Fieldhunter/2020-ZhanJiang-Underwater-Object-Detection-Algorithm-Contest/blob/b3d5e756766cff352acd2a0636e167f09f225514/yolo3/utils.py#L139
box = np.array([np.array(box[i]) for i in range(len(box))])
box[:, [0,2]] = box[:, [0,2]] + dx
box[:, [1,3]] = box[:, [1,3]] + dy
```
其中，dx和dy是灰条填充前后图像宽高增加的值。这部分代码也许更应该与图像灰条填充代码放在一起比较好，在这里深表歉意。

**Comment by c464851257** [comment]
万分感谢

**Comment by c464851257** [comment]
> > > @c464851257 您好，关于光学的数据集我已上传到Google Drive，您可通过以下地址自行下载：https://drive.google.com/drive/folders/1MHzdxShXW6QdkD_9QmNT9oPUNerMYxDq?usp=sharing
> > 
> > 
> > 谢谢您，还有一个问题，您对数据进行保证图片比例的resize以后边框用灰条填充，label的处理部分在代码里面没有看见呢
> 
> 针对灰条填充后的的label处理是有的，在yolo3/utils.py中：
> 
> ```
> # https://github.com/Fieldhunter/2020-ZhanJiang-Underwater-Object-Detection-Algorithm-Contest/blob/b3d5e756766cff352acd2a0636e167f09f225514/yolo3/utils.py#L139
> box = np.array([np.array(box[i]) for i in range(len(box))])
> box[:, [0,2]] = box[:, [0,2]] + dx
> box[:, [1,3]] = box[:, [1,3]] + dy
> ```
> 
> 其中，dx和dy是灰条填充前后图像宽高增加的值。这部分代码也许更应该与图像灰条填充代码放在一起比较好，在这里深表歉意。

万分感谢，是我没有看到
