### ISSUE TITLE
大佬求分享数据集，跪谢~   cqutreasure@163.com

### ISSUE THREAD

**Issue by mdfang322** [Fieldhunter/2020-ZhanJiang-Underwater-Object-Detection-Algorithm-Contest#4]
大佬求分享数据集，跪谢~   cqutreasure@163.com

**Comment by Fieldhunter** [comment]
> 大佬求分享数据集，跪谢~ [cqutreasure@163.com](mailto:cqutreasure@163.com)

您好，数据集已在过去的一个issue中有给出，您可以在该issue中看到下载链接。#2

**Comment by mdfang322** [comment]
没注意到在closed里面，收到了，感谢
